# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-15 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_author', '0002_auto_20190515_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='notes',
            new_name='note',
        ),
    ]
